import { useI18n } from "@/lib/i18n";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { Link } from "wouter";

const CONTENT = {
    en: `FLOWLIFT PRIVACY POLICY

Last updated: 01/27/2026

This Privacy Policy explains how flowlift (“flowlift”, “we”, “our”, or “us”) collects, uses, stores, and protects personal data when you use our platform and services (the “Platform”).

flowlift is operated by Juan Alanis, acting as an individual business operator (Persona Física con Actividad Empresarial), based in Mexico.

By accessing or using flowlift, you acknowledge that your personal data will be processed in accordance with this Privacy Policy.

1. Data Controller
flowlift
Operated by Juan Alanis
Address: Paseo de la Turquesa #407, San Patricio Plus,
25204 Saltillo, Coahuila, Mexico
📧 Contact: juan.alanis@flowlift.co

2. Scope of This Policy
This Privacy Policy applies to:
Business users who create and manage accounts on flowlift
End customers who interact with booking pages generated by businesses
Visitors to flowlift websites or services

flowlift is a technology platform and booking intermediary. Businesses using flowlift are independent controllers of their customer data.

3. Personal Data We Collect
A. Business Users
We may collect:
Name and business name
Email address
Contact information
Account credentials
Subscription and billing information
Usage and activity data

B. End Customers
Collected on behalf of businesses:
Name
Email address
Booking-related details

⚠️ flowlift does not currently collect payment card data from end customers.
If payment features are enabled in the future, payments will be processed by third-party providers (e.g. Stripe) under their own privacy policies.

4. How We Use Personal Data
We process personal data for the following purposes:
Primary (necessary) purposes
To operate and maintain the Platform
To manage user accounts and bookings
To provide customer support
To send transactional and service-related communications
To comply with legal and regulatory obligations

Secondary (optional) purposes
Product improvement and analytics
Platform performance monitoring
Informational or service-related communications
You may opt out of non-essential communications at any time.

5. Legal Bases for Processing
Depending on the context, we process personal data based on:
Contractual necessity
Legitimate business interests
User consent
Legal obligations

6. Cookies and Tracking Technologies
flowlift may use cookies or similar technologies to:
Ensure platform functionality
Improve user experience
Analyze usage patterns
You can control cookies through your browser settings.

7. Data Sharing and Transfers
flowlift does not sell personal data.
We may share data with:
Infrastructure and hosting providers
Database and analytics services
Payment processors (when applicable)
Legal or regulatory authorities when required

Examples of service providers include Replit, Supabase, and future payment providers such as Stripe.

Data may be processed or stored outside your country of residence. We take reasonable steps to ensure appropriate safeguards are in place.

8. Data Security
flowlift implements reasonable administrative, technical, and organizational measures to protect personal data against unauthorized access, loss, misuse, or alteration.
However, no system is completely secure, and we cannot guarantee absolute security.

9. Data Retention
We retain personal data only for as long as necessary to:
Provide the Platform
Fulfill contractual and legal obligations
Resolve disputes
Enforce our agreements

Upon account termination, access to the Platform may be revoked immediately.

10. User Rights
Depending on your location, you may have rights to:
Access your personal data
Request correction or updates
Request deletion
Object to or restrict processing

Requests may be submitted to juan.alanis@flowlift.co.
We will respond in accordance with applicable law.

11. Business User Responsibilities
Businesses using flowlift are responsible for:
Lawful collection of customer data
Providing their own privacy notices to customers
Ensuring compliance with applicable data protection laws
flowlift acts as a technology provider and data processor with respect to end-customer data.

12. Children’s Data
flowlift is not intended for use by children, and we do not knowingly collect personal data from individuals under the age required by applicable law.

13. Changes to This Privacy Policy
We may update this Privacy Policy from time to time.
Updates will be posted on the Platform and become effective upon publication. Continued use of flowlift constitutes acceptance of the updated policy.

14. Contact Us
If you have questions or requests regarding this Privacy Policy, please contact:
📧 juan.alanis@flowlift.co`,
    es: `AVISO DE PRIVACIDAD INTEGRAL – FLOWLIFT

Última actualización: 27/01/2026

En cumplimiento con lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares y su Reglamento (la “Ley”), se emite el presente Aviso de Privacidad para informar a los usuarios sobre el tratamiento de sus datos personales.

1. Responsable del Tratamiento de los Datos
Juan Alanis, actuando como Persona Física con Actividad Empresarial, con domicilio en Paseo de la Turquesa #407, San Patricio Plus, C.P. 25204, Saltillo, Coahuila, México, es el responsable del tratamiento de los datos personales recabados a través de la plataforma flowlift (la “Plataforma”).
📧 Contacto: juan.alanis@flowlift.co

2. Datos Personales que se Recaban
flowlift podrá recabar los siguientes datos personales:

a) De Negocios (Usuarios de la Plataforma)
Nombre del responsable o representante
Nombre comercial
Correo electrónico
Información de contacto
Datos de uso de la Plataforma
Información de suscripciones y facturación

b) De Clientes Finales
Nombre
Correo electrónico
Información relacionada con reservaciones

⚠️ flowlift no recaba directamente datos financieros de clientes finales.
En el futuro, los pagos podrán ser procesados por terceros (por ejemplo, Stripe), conforme a sus propios avisos de privacidad.

3. Finalidades del Tratamiento
Los datos personales serán utilizados para las siguientes finalidades:

Finalidades primarias (necesarias)
Operar y administrar la Plataforma
Gestionar cuentas de usuarios
Procesar reservaciones
Proveer soporte técnico
Enviar notificaciones relacionadas con el Servicio
Cumplir obligaciones legales

Finalidades secundarias (opcionales)
Mejora del producto
Análisis estadístico
Comunicaciones informativas o promocionales relacionadas con flowlift
El titular podrá oponerse al uso de sus datos para finalidades secundarias enviando un correo a juan.alanis@flowlift.co.

4. Uso de Cookies y Tecnologías Similares
flowlift podrá utilizar cookies, web beacons u otras tecnologías similares para:
Mejorar la experiencia del usuario
Analizar el uso de la Plataforma
Recordar preferencias
El usuario puede deshabilitar estas tecnologías desde su navegador.

5. Transferencias de Datos
flowlift no vende ni renta datos personales.
Los datos podrán ser compartidos únicamente con:
Proveedores tecnológicos necesarios para la operación del Servicio
Plataformas de alojamiento y bases de datos (por ejemplo, Replit y Supabase)
Proveedores de pago en caso de habilitarse dicha funcionalidad
Dichos terceros están obligados a proteger la información conforme a estándares adecuados.

6. Almacenamiento y Seguridad
Los datos personales se almacenan en infraestructura tecnológica de terceros, ubicada fuera o dentro del territorio nacional.
flowlift implementa medidas administrativas, técnicas y físicas razonables para proteger los datos personales contra daño, pérdida, alteración o uso no autorizado.

7. Derechos ARCO
El titular de los datos personales tiene derecho a:
Acceder a sus datos
Rectificarlos si son inexactos
Cancelarlos
Oponerse a su tratamiento
Para ejercer los derechos ARCO, deberá enviar una solicitud al correo juan.alanis@flowlift.co, indicando:
Nombre del titular
Derecho que desea ejercer
Descripción clara de la solicitud
La respuesta se dará conforme a los plazos establecidos en la Ley.

8. Responsabilidad de los Negocios
Los Negocios que utilicen flowlift son responsables independientes del tratamiento de los datos personales de sus clientes.
flowlift actúa únicamente como encargado tecnológico, y no es responsable por el uso que cada Negocio haga de dicha información.

9. Cambios al Aviso de Privacidad
flowlift podrá modificar el presente Aviso de Privacidad en cualquier momento.
Las modificaciones serán publicadas en la Plataforma y entrarán en vigor desde su publicación.

10. Consentimiento
Al utilizar la Plataforma, el Usuario otorga su consentimiento expreso para el tratamiento de sus datos personales conforme a este Aviso de Privacidad.

Contacto
📧 juan.alanis@flowlift.co`
};

export default function PrivacyPolicy() {
    const { language, t } = useI18n();
    const content = CONTENT[language as keyof typeof CONTENT] || CONTENT.en;

    return (
        <div className="min-h-screen bg-white">
            <header className="sticky top-0 z-50 bg-white border-b h-20 flex items-center">
                <div className="container mx-auto px-4 flex items-center justify-between">
                    <Link href="/">
                        <div className="flex items-center gap-2 group cursor-pointer text-gray-600 hover:text-black font-semibold">
                            <ArrowLeft className="h-5 w-5 transition-transform group-hover:-translate-x-1" />
                            {t("common.back")}
                        </div>
                    </Link>
                    <h1 className="text-xl font-bold font-serif">{t("nav.privacyPolicy")}</h1>
                    <div className="w-20" /> {/* Spacer */}
                </div>
            </header>

            <main className="container mx-auto px-4 py-16 max-w-4xl">
                <div className="prose prose-slate max-w-none font-sans">
                    {content.split('\n').map((line, i) => (
                        <p key={i} className={line.match(/^[0-9]+\.|^[A-Z]\./) ? "font-bold mt-8 text-xl" : "mb-4"}>
                            {line}
                        </p>
                    ))}
                </div>
            </main>
        </div>
    );
}
